# Generated by Django 5.0.2 on 2024-03-24 10:40

import micro.jango.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('deleted', models.DateTimeField(null=True)),
                ('deleter_id', models.CharField(default='', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator_id', models.CharField(default='', max_length=20)),
                ('updater_id', models.CharField(default='', max_length=20)),
                ('id', micro.jango.models.fields.ShortIdField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=11, max_length=20, prefix='T', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_open', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
    ]
